default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: readr_development
test:
  <<: *default
  database: readr_test
production:
  <<: *default
  database: readr_production
  username: readr
  password: <%= ENV['READR_DATABASE_PASSWORD'] %>
